version: '3'

services:
  frontend:
    build:
      context: ./fe  # Path to your Node.js application directory
      dockerfile: Dockerfile-fe
    ports:
      - "5173:5173"  # Expose the Node.js app's port
    networks:
      - app_network

  backend:
    build:
      context: ./be  # Path to your Python application directory
      dockerfile: Dockerfile-be
    networks:
      - app_network

networks:
  app_network:
    driver: bridge