# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your project files to the container
COPY . .

# Build your project (adjust this according to your build process)
RUN npm run build

# Expose the port your app runs on (if applicable)
EXPOSE 5173

# Start your application
CMD [ "npm", "run", "dev" ]
