FROM python:3.11
SHELL ["/bin/bash", "-c"]
LABEL maintainer="Romeo Delinicolas <Romeo.Delinicolas@gmail.com>"

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /application
RUN chown www-data:www-data /application
ENV PYTHONPATH $PYTHONPATH:/application
RUN apt-get --yes clean && apt-get -yqq --fix-missing update && apt-get -yqq install build-essential curl locales locate cron supervisor
RUN apt-get -yqq install libtbb-dev libgflags-dev libgoogle-glog-dev libgtest-dev libssl-dev git swig
RUN apt-get update
RUN apt-get -yqq install software-properties-common

WORKDIR /python-prod
COPY requirements.txt ./

ARG pip_install="python3.11 -m  pip install"

RUN ${pip_install} -U pip
RUN ${pip_install} pyodbc
RUN python3 -m pip list
RUN ${pip_install} -r requirements.txt
COPY . .

CMD python3.11 main.py "When is Census Date?"
